name: Analyze batch by Copilot agent
on:
  workflow_dispatch:

jobs:
  export_and_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Install Playwright browsers
        run: python -m playwright install chromium
      - name: Export articles for agent
        run: python scripts/export_for_agent.py
      - name: Upload exported JSON
        uses: actions/upload-artifact@v4
        with:
          name: for_copilot_json
          path: reports/for_copilot_*.json
      - name: Request Copilot agent to analyze (placeholder)
        run: echo "#github-pull-request_copilot-coding-agent Request: analyze exported JSON and create report artifact"
