name: Export articles and request Copilot analysis

on:
  workflow_dispatch: {}

jobs:
  export-and-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export scraped JSON
        run: |
          python scripts/analyze_batch_job.py

      - name: Upload scraped artifact
        uses: actions/upload-artifact@v4
        with:
          name: scraped_for_copilot
          path: reports/scraped_for_copilot_*.json

      - name: Create analysis request issue for Copilot
        uses: actions/github-script@v7
        with:
          script: |
            const ts = new Date().toISOString();
            const artifactName = 'scraped_for_copilot';
            const body = `Please run the external analysis agent (Copilot coding agent) on the artifact '${artifactName}'.\n\nGuidelines: see AGENT_INSTRUCTIONS.md in this repository.\n\nWhen finished, upload the result as an artifact named 'for_copilot_analyzed_<timestamp>.json' or commit the file to 'reports/'.`;
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Agent analysis request: ${ts}`,
              body: body
            })

# Notes for maintainers:
# - This workflow exports the scraped JSON and creates a GitHub issue to signal an external agent.
# - The Copilot coding agent (or other external process) should download the artifact from the Actions run, produce 'for_copilot_analyzed_<ts>.json', and either upload it as an artifact or commit it to 'reports/'.
# - A separate workflow (or a manual run) can import the analyzed JSON using: `python scripts/import_agent_results.py reports/for_copilot_analyzed_<ts>.json`.
